stages:
  - build

build_linux:
  stage: build
  tags:
    - linux
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/

build_windows:
  stage: build
  tags:
    - windows
  script:
    - ./gradlew.bat build
  artifacts:
    paths:
      - build/libs/

build_mac:
  stage: build
  tags:
    - mac
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/
