name: Release with jpackage

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
      - name: Build Linux DEB
        run: ./gradlew jpackage -Djpackage.type=deb
      - name: Upload .deb to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/jpackage/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
      - name: Build Windows EXE
        run: ./gradlew jpackage -Djpackage.type=exe
      - name: Upload .exe to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/jpackage/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  build-macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: 23
#      - name: Build macOS DMG
#        run: ./gradlew jpackage -Djpackage.type=dmg
#      - name: Upload .dmg to release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: build/jpackage/*.dmg
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
